---
- hosts: all
  become: true
  tasks:

  - name: install apache2 package
   #ansible.builtin.apt:
    ansible.builtin.package: 
      name: 
      # - apache2
      # - libapache2-mod-php
        - "{{ apache_package }}"
        - "{{ php_package }}"
      state: latest
      update_cache: yes
#    when: ansible_distribution == "Ubuntu"

 # - name: install httpd package
 #   ansible.builtin.dnf:
 #     name:
 #       - httpd
 #       - php
 #     state: latest
 #     update_cache: yes
 #   when: ansible_distribution == "Fedora"

